### ISSUE TITLE
Disable on development builds

### ISSUE THREAD

**Issue by tkapusta** [CarterGames/BuildVersions#2]
Hello!
First for the great asset! I was tired by changing the Android version every time I upload game to Play store so I really appreciate!
I have an idea for a feature request:
add a setting to disable incrementing build number on development builds. I am testing my game using "Patch and run" multiple times a day, and every time I have to click "no" on prompts, or silently agree to increment number. And I would like to have version number increased only when I do release builds. Is this something possible for you to add? 

Thanks again, and have a good day!

**Comment by JonathanMCarter** [comment]
Hi, sorry for the really late reply, I never got a notification on this. 

Yea, I'll have a look into adding a toggle for this purpose in the next release.

**Comment by tkapusta** [comment]
Thank you, I appreciate your work!

**Comment by JonathanMCarter** [comment]
The feature is in the release I've just pushed up 1.2.0. Was about to release it before I spotted your issue so just added it in to this release. Should stop the asset from running if you are making a development build (in the build settings of Unity) with the asset toggled to not run on dev builds.
